#!/usr/bin/env python3
"""
gen-tuning-numbers.py

Reads the `CFG` object from index.html and regenerates
docs/architecture/tuning-numbers.md (or appends a generated section).

Why: the doc is hand-written and drifts from code. This script
extracts values AND their `// comments` directly from the code, so
the generated section is always in sync.

Usage:
  python3 gen-tuning-numbers.py              # print to stdout
  python3 gen-tuning-numbers.py --write      # update the doc
  python3 gen-tuning-numbers.py --check      # exit 1 if drift detected

Strategy:
- Parse `// comments` from CFG values to get human descriptions
- Format as a table grouped by category (Economy, Buildings, Drone, etc.)
- The hand-written sections above remain (they have context the parser can't see)
"""

import re
import sys
import os
from pathlib import Path

# ───────────────────────────────────────────────────────────
# Locate files
# ───────────────────────────────────────────────────────────
SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent.parent.parent
INDEX = REPO_ROOT / "index.html"
DOC = REPO_ROOT / "docs" / "architecture" / "tuning-numbers.md"


def parse_cfg_from_index():
    """Extract the CFG object as nested dict with comments preserved.

    Returns: {
      'flat_keys': {
        'STARTING_CREDITS': {'value': 200, 'comment': 'enough for...'},
        'CFG.DRONE.BLAST_RADIUS': {'value': 60, 'comment': 'pixels'},
        ...
      },
      'sections': {
        'ECONOMY': ['STARTING_CREDITS', 'PASSIVE_INCOME', ...],
        'BUILDINGS': ['BARRACKS_COST', ...],
        'DRONE': ['CFG.DRONE.BLAST_RADIUS', ...],
        ...
      }
    }
    """
    text = INDEX.read_text()

    # Find the CFG block: "const CFG = {" ... "};"
    m = re.search(r"const CFG = \{(.*?)\n\};", text, re.DOTALL)
    if not m:
        print("ERROR: could not find CFG block in index.html", file=sys.stderr)
        sys.exit(2)

    cfg_text = m.group(1)
    flat_keys = {}
    sections = {}

    current_section = "GENERAL"
    current_nested = None  # e.g. "DRONE" when inside CFG.DRONE = { ... }

    for line in cfg_text.split("\n"):
        # Detect section comments like "// ────── DRONE ──────"
        sec_match = re.search(r"//\s*─+\s*([A-Z][A-Z _]+)\s*─+", line)
        if sec_match:
            current_section = sec_match.group(1).strip()
            current_nested = None
            sections.setdefault(current_section, [])
            continue

        # Detect nested block start: "DRONE: {"
        nest_match = re.match(r"^\s*([A-Z_]+):\s*\{", line)
        if nest_match:
            current_nested = nest_match.group(1)
            sections.setdefault(current_nested, [])
            continue

        # Detect end of nested block: closing "}" with no value
        if re.match(r"^\s*\},?\s*(?://.*)?$", line):
            current_nested = None
            continue

        # Parse a key-value line: "  KEY: 123,   // comment"
        kv_match = re.match(r"^\s*([A-Z_][A-Z0-9_]*):\s*([^,]+),\s*(?://\s*(.*))?$", line)
        if kv_match:
            key = kv_match.group(1)
            value = kv_match.group(2).strip()
            comment = kv_match.group(3) or ""

            # Try to parse value as number
            try:
                numeric_value = float(value)
                if numeric_value == int(numeric_value):
                    numeric_value = int(numeric_value)
            except ValueError:
                numeric_value = value

            # Compose fully qualified key
            if current_nested:
                full_key = f"{current_nested}.{key}"
                sections.setdefault(current_nested, []).append(full_key)
            else:
                full_key = key
                sections.setdefault(current_section, []).append(full_key)

            flat_keys[full_key] = {
                "value": numeric_value,
                "comment": comment.strip(),
            }

    return flat_keys, sections


def format_value(v):
    """Format a value for display."""
    if isinstance(v, float):
        if v == int(v):
            return str(int(v))
        return str(v)
    return str(v)


def generate_markdown(flat_keys, sections):
    """Generate the AUTO-GENERATED section."""
    lines = []
    lines.append("## 🤖 Auto-Generated CFG Reference")
    lines.append("")
    lines.append("> **This section is generated by `docs/audit/scripts/gen-tuning-numbers.py`.**")
    lines.append("> Do not edit by hand. To update, run: `python3 gen-tuning-numbers.py --write`")
    lines.append("> The `// comments` after each value in `index.html` become the Description column.")
    lines.append("")

    # Skip UNITS and BUILDING_TREE — those are tables elsewhere
    SKIP = {"UNITS", "BUILDING_TREE", "BARRACKS_UNITS", "WARFACTORY_UNITS",
            "TECHCENTER_UNITS", "PROD_MULT"}

    for section_name in sections:
        keys = sections[section_name]
        # Filter out skipped
        keys = [k for k in keys if k.split(".")[-1] not in SKIP]
        if not keys:
            continue

        # Pretty section title
        title = section_name.replace("_", " ").title()

        lines.append(f"### {title}")
        lines.append("")
        lines.append("| Key | Value | Description |")
        lines.append("|---|---|---|")

        for full_key in keys:
            if full_key not in flat_keys:
                continue
            entry = flat_keys[full_key]
            val = format_value(entry["value"])
            comment = entry["comment"] or "—"
            lines.append(f"| `{full_key}` | {val} | {comment} |")

        lines.append("")

    return "\n".join(lines)


def main():
    write = "--write" in sys.argv
    check = "--check" in sys.argv

    flat_keys, sections = parse_cfg_from_index()
    md = generate_markdown(flat_keys, sections)

    if check:
        # Check if doc contains this section
        if not DOC.exists():
            print("ERROR: tuning-numbers.md not found", file=sys.stderr)
            sys.exit(2)

        existing = DOC.read_text()
        if "## 🤖 Auto-Generated CFG Reference" not in existing:
            print("⚠️  Auto-generated section not in doc. Run --write to add it.")
            sys.exit(1)
        # Extract existing section
        m = re.search(
            r"## 🤖 Auto-Generated CFG Reference(.*?)(?=\n## |\Z)",
            existing, re.DOTALL
        )
        if not m:
            print("⚠️  Could not extract existing section.")
            sys.exit(1)
        existing_section = m.group(0).strip()
        new_section = md.strip()
        if existing_section == new_section:
            print(f"✅ Doc is in sync with code ({len(new_section)} bytes).")
            sys.exit(0)
        else:
            print("❌ Doc has drifted from code. Run --write to fix.")
            print(f"   Existing: {len(existing_section)} bytes")
            print(f"   Expected: {len(new_section)} bytes")
            sys.exit(1)

    if write:
        existing = DOC.read_text() if DOC.exists() else ""
        # Replace the auto-generated section (or append it)
        if "## 🤖 Auto-Generated CFG Reference" in existing:
            new_doc = re.sub(
                r"## 🤖 Auto-Generated CFG Reference.*?(?=\n## |\Z)",
                md.rstrip(),
                existing,
                flags=re.DOTALL
            )
        else:
            new_doc = existing.rstrip() + "\n\n" + md

        DOC.write_text(new_doc)
        print(f"✅ Wrote {len(new_doc)} bytes to {DOC}")
        return

    # Default: print to stdout
    print(md)


if __name__ == "__main__":
    main()
